[tool.poetry]
name = "standard_workflow"
version = "0.1.0"
authors = ["Edward Huh <edward_huh@brown.edu>"]
description = "standardization of my workflow using the hypermodern Python project"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/edwardhuh/standard_workflow"
repository = "https://github.com/edwardhuh/standard_workflow"
keywords = ["standard"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
